branch-defaults:
  default:
    environment: Mygoodapp-env
environment-defaults:
  Mygoodapp-env:
    branch: null
    repository: null
  Udagramproj-env:
    branch: null
    repository: null
global:
  application_name: my-good-app
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
